# Generated by Django 4.2.1 on 2023-07-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mangement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
